name: CI-CD-Demo-Olivierkab

on:

  push:

    branches:

      - main

permissions:

  contents: write   #  REQUIRED for release creation

jobs:

  build_test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Build (generate artifact)

      run: |

        mkdir -p dist

        echo "Build artifact generated Olivierkab at $(date)" > dist/app.txt

    - name: Test (always pass)

      run: |

        echo "All tests passed"

    - name: Upload Build Artifact

      uses: actions/upload-artifact@v4

      with:

        name: build-artifact

        path: dist/

 release:

    needs: build_test

    runs-on: ubuntu-latest

    steps:

    - name: Download Build Artifact

      uses: actions/download-artifact@v4

      with:

        name: build-artifact

        path: dist/

    - name: Upload to Azure Blob Storage

      uses: azure/cli@v2

      with:

        inlineScript: |

          az storage blob upload \

            --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \

            --container-name demo \

            --file dist/app.txt \

            --name app-${{ github.run_number }}.txt \

            --overwrite
